version: "3.3"

services:
  bash:
    image: jfahrer/myalpine:bash
    build:
      context: .
      cache_from:
        - jfahrer/myalpine:bash

  zsh:
    image: jfahrer/myalpine:zsh
    build:
      context: .
      args:
        - MYSHELL=zsh
      cache_from:
        - jfahrer/myalpine:zsh
