version: '3.3'

services:
  lb:
    image: jfahrer/lb:latest
    environment:
      - PROXY_UPSTREAM=app:9494
    ports:
      - 80:80

  app:
    image: jfahrer/webapp-ruby:latest
    build:
      context: .
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
      - POSTGRES_HOST=pg
    volumes:
      - .:/app

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  client:
    image: jfahrer/checker-u-dev-a3:latest
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
      - POSTGRES_HOST=pg
