version: '3.3'

services:
  app:
    image: jfahrer/webapp-ruby:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 9494:9494

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
