version: "3.4"

services:
  frontend:
    image: jfahrer/swarm-demo-frontend:v10
    env_file:
      - config/app.env
    healthcheck:
      test: curl -f http://localhost:8080/status || false
      interval: 2s
      retries: 3
      start_period: 3s

  db:
    image: postgres:9.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - config/db.env

  lb:
    image: jfahrer/swarm-demo-lb:v1
    environment:
      - PROXY_UPSTREAM=frontend:8080
    ports:
      - 80:80
